name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Vendora.Api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore
